interface InterFaceInfoEquipments {
  id: number;
  model: string;
  status: string;
  stock: number;
  mark: number;
  type: number;
  category: number;
  count: number;
  discount: number;
  tool_number: number;
  selling_price: string;
  price_per_day: string;
  rentals: number;
  repairs: number;
  repairs_sum: string;
  revenue: string;
  profit: string;
  degree_wear: number;
  payback_ratio: number;
  power_energy: string;
  length: string;
  network_cord: string;
  photo: string;
  photo_alias: string;
  power: string;
  frequency_hits: string;
  comment: string;
}
